version: '3.8'

services:
  yttmp3-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: yttmp3-frontend:latest
    container_name: yttmp3-converter
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - PORT=3000
      - HOSTNAME=0.0.0.0
    env_file:
      - .env.local
    ports:
      - "3000:3000"
    volumes:
      # Mount temp directory for file processing
      - ./temp:/app/temp
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - yttmp3-network
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 0.5

  # Nginx reverse proxy (optional, for production)
  nginx:
    image: nginx:alpine
    container_name: yttmp3-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - yttmp3-app
    networks:
      - yttmp3-network
    profiles:
      - production

networks:
  yttmp3-network:
    driver: bridge

volumes:
  temp-data:
