services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: yt-mp3-frontend:latest
    environment:
      - NODE_ENV=production
      # Add your YouTube cookies here as base64 encoded string
      # To get cookies: Use browser extension "Get cookies.txt LOCALLY"
      # Then encode: cat cookies.txt | base64 -w 0
      - YTDLP_COOKIES_BASE64=${YTDLP_COOKIES_BASE64:-}
      # Alternative: Set via .env file (more secure)
    env_file:
      - .env.local
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "wget", "-qO", "-", "http://localhost:3000" ]
      interval: 30s
      timeout: 5s
      retries: 5
    restart: unless-stopped
